//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public int AccountId { get; set; }
        public string Text { get; set; }
        public decimal Amount { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
